#!/bin/sh

. /Users/rafael/Documents/MagentoLearning/scripts/setenv.sh

exec /Users/rafael/Documents/MagentoLearning/php/sbin/.php-fpm.bin -y /Users/rafael/Documents/MagentoLearning/php/etc/php-fpm.conf -p /Users/rafael/Documents/MagentoLearning/php/var/ -c /Users/rafael/Documents/MagentoLearning/php/etc/php.ini "$@"
